apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  namespace: demo-chaos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - name: svc-a
          image: svc-a:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SVC_NAME
              value: svc-a
            - name: DOWNSTREAM_URL
              value: http://svc-b.demo-chaos.svc.cluster.local
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
  namespace: demo-chaos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
        - name: svc-b
          image: svc-b:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SVC_NAME
              value: svc-b
            - name: DOWNSTREAM_URL
              value: http://svc-c.demo-chaos.svc.cluster.local
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-c
  namespace: demo-chaos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-c
  template:
    metadata:
      labels:
        app: svc-c
    spec:
      containers:
        - name: svc-c
          image: svc-c:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SVC_NAME
              value: svc-c
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
