apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: demo-chaos
spec:
  type: NodePort
  selector:
    app: svc-a
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: demo-chaos
spec:
  selector:
    app: svc-b
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-c
  namespace: demo-chaos
spec:
  selector:
    app: svc-c
  ports:
  - name: http
    port: 80
    targetPort: 3000
